language: php
os:
  - linux

cache:
  directories:
    - $HOME/.composer/cache/files

jobs:
  fast_finish: true
  include:
    - php: 7.2
      dist: bionic
    - php: 7.2
      dist: bionic
      env: deps=low
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic

install:
  - if [ "$deps" == "low" ]; then travis_retry composer update --prefer-dist --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then travis_retry composer install --prefer-dist; fi

script:
  - vendor/bin/phpstan analyse
